services:
  tile38:
    image: tile38/tile38:latest
    container_name: tile38
    ports:
      - target: 9851
        published: "9851"
        host_ip: "127.0.0.1"
        protocol: tcp
    volumes:
      - tile38-data:/data
    restart: unless-stopped

volumes:
  tile38-data: